### PR TITLE
Update RPM_REPO_OPENSHIFT_ORIGIN url to be release-specific

### PR DESCRIPTION
**Pull request by vrutkovs**
New routes are being used to serve version-specific rpms. This also adds more tests to ensure generated URL is correct

### CODE REVIEW

**Review by stevekuznetsov — COMMENTED** [review]
I'd like to see tests that reflect what we actually want to see in the jobs

**Comment by stevekuznetsov** [comment]
This LGTM but I can't actually speak to the official RPM values

/assign @smarterclayton

**Comment by smarterclayton** [comment]
/hold

This is not correct.  The point of `rpms....` is to provide the repo that is relative.  This change loses that.

**Comment by smarterclayton** [comment]
Let me ask - why did you make this change?

**Comment by vrutkovs** [comment]
Ah, I see, checked sources of artifacts-rpm container - and its a simple proxy which redirects to these urls. Closing

**Comment by vrutkovs** [comment]
A better way to fix that is https://github.com/openshift/release/pull/3777

**Pull request closed without merging**
