### PR TITLE
Only generate `--promote` jobs on those that have promotion config

### PR DESCRIPTION
**Pull request by smarterclayton**
All jobs in openshift/release now have explicit promotion config.

### CODE REVIEW

**Comment by smarterclayton** [comment]
openshift/release has already been set up so all jobs have defaults (this is a no-op on regen) as of last night.  No promotion-config = no promote

**Comment by smarterclayton** [comment]
@bbguimaraes @petr-muller

**Comment by stevekuznetsov** [comment]
Gotta pass tests!

**Comment by smarterclayton** [comment]
I use `make install` too much, always forget that doesn't run tests.

**Comment by smarterclayton** [comment]
Fixed

**Review by petr-muller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
