### PR TITLE
update modules

### PR DESCRIPTION
**Pull request by droslean**
Updating modules to fix pj-rehearse error:

```
ERROR: logging before flag.Parse: E0429 08:18:00.532327      14 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1.ProwJob.Spec: v1.ProwJobSpec.DecorationConfig: v1.DecorationConfig.GracePeriod: readUint64: unexpected character: �, error found in #10 byte of ...|_period":"15s","skip|..., bigger context ...|gce-sa-credentials-gcs-publisher","grace_period":"15s","skip_cloning":true,"timeout":"4h0m0s","utili|...
```

### CODE REVIEW

**Comment by bbguimaraes** [comment]
/lgtm
/hold

Let's have a PR ready for `openshift/release`.

**Comment by droslean** [comment]
related to [release/pull/3627](https://github.com/openshift/release/pull/3627)

**Pull request merged**
