### PR TITLE
The new upgrade job is supported as part of the ci-operator

### PR DESCRIPTION
**Pull request by smarterclayton**
Instead of mounting the template, the ci-operator can run the job itself.
Use the upgrade=true flag only to test this logic while we verify that
upgrade tests (and their attendant complexity) don't destabilize other
jobs.

Examples of the job generated by this PR are in openshift/release#3030.  Will be testing openshift/ci-operator#288 before we merge

### CODE REVIEW

**Comment by smarterclayton** [comment]
@droslean

**Comment by droslean** [comment]
@smarterclayton That seems to caused by bumping the ci-operator libraries,
Can you remove those `canonical_go_repository: ""` from `test/pj-rehearse-integration/expected_jobs.yaml` in this PR?

**Comment by smarterclayton** [comment]
Oh, I thought this was rehearsing against the real repositories.  Duh, fixing.

**Comment by smarterclayton** [comment]
Fixed

**Pull request merged**
