### PR TITLE
Generated openshift-ansible tests for 4.0 should use scaleup

### PR DESCRIPTION
**Pull request by vrutkovs**
Scaleup is a primary target for openshift-ansible in this release

### CODE REVIEW

**Comment by petr-muller** [comment]
This will need a matching PR to openshift/release, if we have at least one job affected by this (haven't looked).

**Comment by petr-muller** [comment]
/approve
/lgtm
/hold

Holding to allow preparing the openshift/release PR or confirming it's not needed.

**Comment by vrutkovs** [comment]
Release PR - https://github.com/openshift/release/pull/2964

**Pull request merged**
