### PR TITLE
rehearse: split messages into different levels

### PR DESCRIPTION
**Pull request by bbguimaraes**
Sample output:

<details>

```
INFO[0000] Rehearsing Prow jobs for a configuration PR   pr=2367
DEBU[0000] Rehearsal job uses ci-operator config ConfigMap, needed content will be inlined  ciop-config-file=openshift-ci-operator-master.yaml ciop-config-repo=openshift/ci-operator pr=2367 rehearsal-job=rehearse-2367-pull-ci-openshift-ci-operator-master-build target-job=pull-ci-openshift-ci-operator-master-build target-repo=openshift/ci-operator
INFO[0000] Created a rehearsal job to be submitted       pr=2367 rehearsal-job=rehearse-2367-pull-ci-openshift-ci-operator-master-build target-job=pull-ci-open shift-ci-operator-master-build target-repo=openshift/ci-operator
INFO[0000] Submitting a new prowjob.                     job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=886f6dcf-20d8-11e9-b870-e86a6403f52c org=openshift pr=2367 repo=release type=presubmit
INFO[0000] Submitted rehearsal prowjob                   job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=886f6dcf-20d8-11e9-b870-e86a6403f52c org=openshift pr=2367 repo=release type=presubmit
DEBU[0001] Processing ProwJob                            job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=13c4f05f-20d6-11e9-a542-e86a6403f52c org=openshift pr=2367 repo=release state=failure type=presubmit
DEBU[0001] Processing ProwJob                            job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=49b4ee8a-20d0-11e9-97ed-e86a6403f52c org=openshift pr=2367 repo=release state=failure type=presubmit
DEBU[0002] Processing ProwJob                            job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=886f6dcf-20d8-11e9-b870-e86a6403f52c org=openshift pr=2367 repo=release state=triggered type=presubmit
DEBU[0002] Processing ProwJob                            job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=88d49299-20d0-11e9-a0fa-e86a6403f52c org=openshift pr=2367 repo=release state=failure type=presubmit
DEBU[0003] Processing ProwJob                            job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=dac57281-20d6-11e9-8db0-e86a6403f52c org=openshift pr=2367 repo=release state=failure type=presubmit
DEBU[0019] Processing ProwJob                            job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=886f6dcf-20d8-11e9-b870-e86a6403f52c org=openshift pr=2367 repo=release state=pending type=presubmit
DEBU[0048] Processing ProwJob                            job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=886f6dcf-20d8-11e9-b870-e86a6403f52c org=openshift pr=2367 repo=release state=failure type=presubmit
ERRO[0048] Job failed                                    job=rehearse-2367-pull-ci-openshift-ci-operator-master-build name=886f6dcf-20d8-11e9-b870-e86a6403f52c org=openshift pr=2367 repo=release state=failure type=presubmit
ERRO[0048] Failed to execute rehearsal jobs              error="not all ProwJobs were successful" pr=2367
```

</details>

### CODE REVIEW

**Review by stevekuznetsov — COMMENTED** [review]
/lgtm
/hold
You have a TODO still?

**Comment by bbguimaraes** [comment]
The TODO refers to the incorrect `const` types we discussed last week.

I have opened a [PR](https://github.com/kubernetes/test-infra/pull/10992) upstream to fix them.

**Comment by bbguimaraes** [comment]
The upstream PR was merged, this PR now also updates the `vendor` directory to include the changes and fixes the `TODO` (otherwise left unchanged).

**Pull request merged**
